### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Fan7asy** [Fan7asy/OgarFeederBot#1]
- [ ] Fully fix the bot.
- [ ] Implement multi-user support
- [ ] Expand client capabilities

**Comment by josefredohd** [comment]
don't work in gota.io
